import {
  ClipEntry,
  ClipState,
  GPUJob,
  JobType,
  JobStatus,
  GPUInfo,
} from "./types";

export const MOCK_CLIPS: ClipEntry[] = [
  {
    id: "clip-001",
    name: "Woman_Jumps_Fx_pro_uhd",
    state: ClipState.COMPLETE,
    frameCount: 478,
    currentFrame: 234,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-002",
    name: "Car_Chase_GS_4k",
    state: ClipState.READY,
    frameCount: 1200,
    currentFrame: 0,
    inPoint: 100,
    outPoint: 800,
    thumbnailUrl: null,
    warnings: ["Alpha hint has 2 missing frames"],
    errorMessage: null,
  },
  {
    id: "clip-003",
    name: "Explosion_Test_v3",
    state: ClipState.RAW,
    frameCount: 360,
    currentFrame: 0,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-004",
    name: "Hero_Landing_GS_v2",
    state: ClipState.EXTRACTING,
    frameCount: 890,
    currentFrame: 0,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-005",
    name: "Sword_Fight_4k_final",
    state: ClipState.MASKED,
    frameCount: 1540,
    currentFrame: 0,
    inPoint: 200,
    outPoint: 1400,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-006",
    name: "Dragon_Flyby_uhd",
    state: ClipState.READY,
    frameCount: 720,
    currentFrame: 0,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: ["Low contrast green screen", "Frame 412 corrupt"],
    errorMessage: null,
  },
  {
    id: "clip-007",
    name: "Hallway_Walk_prores",
    state: ClipState.ERROR,
    frameCount: 300,
    currentFrame: 0,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: "CUDA out of memory at frame 187",
  },
  {
    id: "clip-008",
    name: "Rooftop_Jump_GS_8k",
    state: ClipState.COMPLETE,
    frameCount: 240,
    currentFrame: 240,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-009",
    name: "Lab_Scene_Beakers_v4",
    state: ClipState.COMPLETE,
    frameCount: 960,
    currentFrame: 960,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-010",
    name: "Motorcycle_Chase_final",
    state: ClipState.RAW,
    frameCount: 2100,
    currentFrame: 0,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-011",
    name: "Spaceship_Interior_GS",
    state: ClipState.COMPLETE,
    frameCount: 1800,
    currentFrame: 1800,
    inPoint: null,
    outPoint: null,
    thumbnailUrl: null,
    warnings: [],
    errorMessage: null,
  },
  {
    id: "clip-012",
    name: "Rain_Scene_Umbrella",
    state: ClipState.READY,
    frameCount: 540,
    currentFrame: 0,
    inPoint: 50,
    outPoint: 490,
    thumbnailUrl: null,
    warnings: ["Alpha hint noisy on frames 200-220"],
    errorMessage: null,
  },
];

export const MOCK_JOBS: GPUJob[] = [
  {
    id: "job-001",
    clipName: "Woman_Jumps_Fx_pro_uhd",
    type: JobType.INFERENCE,
    status: JobStatus.RUNNING,
    progress: 0.49,
    totalFrames: 478,
    currentFrame: 234,
  },
  {
    id: "job-002",
    clipName: "Car_Chase_GS_4k",
    type: JobType.GVM_ALPHA,
    status: JobStatus.QUEUED,
    progress: 0,
    totalFrames: 700,
    currentFrame: 0,
  },
];

export const MOCK_GPU: GPUInfo = {
  name: "RTX 4090",
  vramUsed: 18.2,
  vramTotal: 24.0,
};

// Mock coverage data for the scrubber (frame indices)
export const MOCK_COVERAGE = {
  annotations: [10, 11, 50, 51, 52, 100, 200, 201],
  alphaHints: Array.from({ length: 478 }, (_, i) => i), // all frames
  inferenceOutput: Array.from({ length: 234 }, (_, i) => i), // first 234
};
